---
version: "2.1"
services:
  ipfs_host:
    image: ipfs/go-ipfs:v0.10.0
    container_name: ipfs_host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./ipfsdata:/data/ipfs
      #- ./config:/data/ipfs/config:ro
      - $HOME/ipfs_export:/export
    working_dir: /export  
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    restart: "no"
